#!/usr/bin/env python3
"""Generate the CCMP known-answer vectors in tests/ccmp_vectors.h.

WHY THIS EXISTS. A round-trip test proves an implementation agrees with
itself, which is exactly the property a broken implementation also has. The
AP harness and the station harness both call OpenSSL, so checking one against
the other proves nothing either. These vectors come from a THIRD
implementation — python-cryptography's AESCCM, which is OpenSSL-independent at
the API level and, more importantly, was not written by us — and the 802.11
framing around it is computed here from the standard's rules, independently of
src/sta/Ccmp.h rather than by calling it.

So a divergence between this file and Ccmp.h is a real disagreement between
two independent transcriptions of 802.11-2016 12.5.3.3, which is the only
thing a "known answer" can honestly mean without an official IEEE vector to
hand. It is weaker than the IEEE Annex J vector and stronger than a
round-trip; the selftest's header says so, and swapping in the official vector
later is a drop-in improvement.

Regenerate:  python3 tests/ccmp_gen_vectors.py > tests/ccmp_vectors.h
The output is deterministic — the inputs below are fixed, not random.
"""
import sys

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESCCM
except ImportError:
    sys.exit("needs python-cryptography (pip install cryptography)")


def ccmp_aad(hdr):
    """802.11-2016 12.5.3.3.3, transcribed from the standard, not from Ccmp.h."""
    fc = hdr[0] | (hdr[1] << 8)
    fc &= ~0x0070              # subtype
    fc &= ~0x0800              # retry
    fc &= ~0x1000              # pwr mgmt
    fc &= ~0x2000              # more data
    fc |= 0x4000               # protected
    seq = (hdr[22] | (hdr[23] << 8)) & 0x000F   # keep fragment, mask seq num
    return bytes([fc & 0xFF, fc >> 8]) + bytes(hdr[4:22]) + \
        bytes([seq & 0xFF, seq >> 8])


def ccmp_nonce(a2, pn):
    """12.5.3.3.4: flag octet, A2, then PN big-endian."""
    return bytes([0]) + bytes(a2) + bytes((pn >> (8 * (5 - i))) & 0xFF
                                          for i in range(6))


def ccmp_hdr(pn, key_id):
    return bytes([
        pn & 0xFF, (pn >> 8) & 0xFF, 0x00,
        0x20 | ((key_id & 3) << 6),
        (pn >> 16) & 0xFF, (pn >> 24) & 0xFF,
        (pn >> 32) & 0xFF, (pn >> 40) & 0xFF,
    ])


def c_array(name, data):
    body = ',\n    '.join(
        ', '.join('0x%02x' % b for b in data[i:i + 12])
        for i in range(0, len(data), 12))
    return 'static const uint8_t %s[%d] = {\n    %s\n};\n' % (
        name, len(data), body)


CASES = [
    # (label, tk, a2, pn, key_id, hdr, plaintext)
    ('basic', bytes(range(0x10, 0x20)),
     bytes.fromhex('02424475d600'), 0x000000000001, 0,
     bytes.fromhex('0842000002aabbccddee02424475d60002424475d6000000'),
     bytes.fromhex('aaaa030000000800') + b'devourer station mode'),
    # A frame whose FC carries every bit the AAD is supposed to mask, so a
    # transcription that forgets one of them cannot pass.
    ('masked_fc', bytes.fromhex('c97c1f67ce371185514a8a19f2bdd52f'),
     bytes.fromhex('0011223344 55'.replace(' ', '')), 0x0b5039768834, 2,
     bytes.fromhex('58b3000012340011223344556677889900aa3412'.ljust(48, '0')),
     b'\x01\x02\x03\x04'),
    # Non-zero fragment number: the AAD keeps it while masking the sequence
    # number, which is the half of that rule most likely to be dropped.
    ('fragment', bytes(16),
     bytes.fromhex('020000000001'), 0xffffffffffff, 1,
     bytes.fromhex('0842000002000000000202000000000102000000000175f0'),
     b'x' * 64),
]

print('/* GENERATED by tests/ccmp_gen_vectors.py - do not edit.')
print(' *')
print(' * CCMP known-answer vectors. The ciphertext and MIC come from')
print(' * python-cryptography\'s AESCCM and the 802.11 framing is computed in')
print(' * that script straight from 802.11-2016 12.5.3.3 - independently of')
print(' * src/sta/Ccmp.h, which is the point. A disagreement is two')
print(' * transcriptions of the standard differing, not a round-trip that')
print(' * cannot fail. See the script header for what this is and is not. */')
print('#ifndef DEVOURER_TESTS_CCMP_VECTORS_H')
print('#define DEVOURER_TESTS_CCMP_VECTORS_H')
print()
print('#include <cstdint>')
print('#include <cstddef>')
print()
print('struct CcmpVector {')
print('  const char* name;')
print('  const uint8_t* tk;')
print('  const uint8_t* a2;')
print('  uint64_t pn;')
print('  uint8_t key_id;')
print('  const uint8_t* hdr;')
print('  const uint8_t* plain;  size_t plain_len;')
print('  const uint8_t* mpdu;   size_t mpdu_len;   /* hdr|ccmp|ct|mic */')
print('};')
print()

entries = []
for label, tk, a2, pn, kid, hdr, plain in CASES:
    assert len(hdr) == 24, (label, len(hdr))
    aad = ccmp_aad(hdr)
    nonce = ccmp_nonce(a2, pn)
    blob = AESCCM(tk, tag_length=8).encrypt(nonce, plain, aad)
    prot = bytearray(hdr)
    prot[1] |= 0x40
    mpdu = bytes(prot) + ccmp_hdr(pn, kid) + blob
    print(c_array('kTk_' + label, tk))
    print(c_array('kA2_' + label, a2))
    print(c_array('kHdr_' + label, hdr))
    print(c_array('kPlain_' + label, plain))
    print(c_array('kMpdu_' + label, mpdu))
    entries.append('  {"%s", kTk_%s, kA2_%s, 0x%012xULL, %d, kHdr_%s,\n'
                   '   kPlain_%s, sizeof kPlain_%s, kMpdu_%s, sizeof kMpdu_%s},'
                   % (label, label, label, pn, kid, label, label, label,
                      label, label))

print('static const CcmpVector kCcmpVectors[] = {')
print('\n'.join(entries))
print('};')
print('static const size_t kCcmpVectorCount =')
print('    sizeof kCcmpVectors / sizeof kCcmpVectors[0];')
print()
print('#endif /* DEVOURER_TESTS_CCMP_VECTORS_H */')
